[package]
name = "hexgem_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26.2"
egui_gl_glfw = "0.1.1"
gl = "0.14.0"
glfw = "0.55.0"
log = "0.4.20"


